import React from 'react';
import { AlertTriangle, BookOpen, Edit2, Trash2 } from 'lucide-react';
import {
  Table,
  TableHeader,
  TableBody,
  TableHead,
  TableRow,
  TableCell,
} from '@/components/ui/table';
import TableShimmer from '@/components/ui/TableShimmer';
import { Button } from '@/components/ui/button';
import EmptyState from './EmptyState';
import {
  CATEGORY_DOTS,
  CATEGORY_LABELS,
  SOURCE_LABELS,
  formatCurrency,
  formatDate,
  getDriverName,
  getVehicleLabel,
} from '../utils';

export const CategoryTag = ({ category }) => (
  <span className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-md bg-muted px-2 py-0.5 text-xs font-medium text-foreground">
    <span
      className={`h-1.5 w-1.5 shrink-0 rounded-full ${CATEGORY_DOTS[category] || CATEGORY_DOTS.MISCELLANEOUS}`}
    />
    {CATEGORY_LABELS[category] || category || '—'}
  </span>
);

export const SourceTag = ({ source }) => (
  <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
    {SOURCE_LABELS[source] || source}
  </span>
);

/**
 * The merged transaction table, shared by the All Transactions page and both
 * drill-down ledgers. Only manual rows are editable — everything else is
 * generated by trips, fuel logs, or maintenance and is read-only here.
 */
const LedgerTable = ({
  rows = [],
  loading = false,
  showTrip = false,
  showActions = false,
  onEdit,
  onDelete,
  empty,
}) => {
  const columnCount = 7 + (showTrip ? 1 : 0) + (showActions ? 1 : 0);

  if (loading) return <TableShimmer columns={columnCount} rows={8} />;

  if (rows.length === 0) {
    return (
      empty || (
        <EmptyState
          icon={BookOpen}
          title="No transactions in this period"
          hint="Try widening the date range or clearing a filter."
        />
      )
    );
  }

  return (
    <div className="w-full overflow-x-auto">
      <Table>
        <TableHeader className="sticky top-0 z-10 bg-card">
          <TableRow>
            <TableHead className="whitespace-nowrap">Date</TableHead>
            <TableHead>Details</TableHead>
            <TableHead>Category</TableHead>
            <TableHead className="text-right">Amount</TableHead>
            <TableHead>Truck</TableHead>
            <TableHead>Driver</TableHead>
            <TableHead>Source</TableHead>
            {showTrip && <TableHead>Trip</TableHead>}
            {showActions && <TableHead className="text-right">Actions</TableHead>}
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.map((tx) => (
            <TableRow key={`${tx.source}-${tx._id}`}>
              <TableCell className="num whitespace-nowrap text-sm text-muted-foreground">
                {formatDate(tx.expenseDate || tx.date)}
              </TableCell>
              <TableCell className="max-w-xs">
                <p className="truncate text-sm font-medium text-foreground">{tx.title}</p>
                {tx.description && (
                  <p className="mt-0.5 truncate text-xs text-muted-foreground">{tx.description}</p>
                )}
                {tx.mileageFlag && (
                  <span
                    title={tx.mileageFlag.reason}
                    className="mt-1 inline-flex items-center gap-1 rounded border border-amber-300 bg-amber-50 px-1.5 py-0.5 text-[11px] font-medium text-amber-700"
                  >
                    <AlertTriangle size={11} />
                    <span className="num">
                      {tx.mileageFlag.actualKmPerL?.toFixed(2)} vs {tx.mileageFlag.expectedKmPerL} km/L
                    </span>
                  </span>
                )}
              </TableCell>
              <TableCell>
                <CategoryTag category={tx.category} />
              </TableCell>
              <TableCell className="num whitespace-nowrap text-right font-semibold">
                {formatCurrency(tx.amount)}
              </TableCell>
              <TableCell>
                {tx.vehicle ? (
                  <span className="reg-plate">{getVehicleLabel(tx.vehicle)}</span>
                ) : (
                  <span className="text-xs text-muted-foreground">Unattributed</span>
                )}
              </TableCell>
              <TableCell className="whitespace-nowrap text-sm">
                {tx.driver ? (
                  getDriverName(tx.driver)
                ) : (
                  <span className="text-xs text-muted-foreground">Unattributed</span>
                )}
              </TableCell>
              <TableCell>
                <SourceTag source={tx.source} />
              </TableCell>
              {showTrip && (
                <TableCell className="num text-sm text-muted-foreground">
                  {tx.trip ? tx.trip.tripNumber || tx.trip._id?.slice(-6) : '—'}
                </TableCell>
              )}
              {showActions && (
                <TableCell className="text-right">
                  {tx.source === 'MANUAL' ? (
                    <div className="flex justify-end gap-1">
                      <Button
                        variant="ghost"
                        size="icon-sm"
                        onClick={() => onEdit?.(tx)}
                        aria-label={`Edit ${tx.title}`}
                      >
                        <Edit2 size={14} />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon-sm"
                        onClick={() => onDelete?.(tx)}
                        aria-label={`Delete ${tx.title}`}
                        className="text-muted-foreground hover:bg-destructive/10 hover:text-destructive"
                      >
                        <Trash2 size={14} />
                      </Button>
                    </div>
                  ) : (
                    <span className="text-xs text-muted-foreground">Auto</span>
                  )}
                </TableCell>
              )}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
};

export default LedgerTable;
