import React, { useState, useEffect, useMemo } from 'react';
import {
    Box, Typography, TextField, InputAdornment, CircularProgress, Alert
} from '@mui/material';
import { Search as SearchIcon } from '@mui/icons-material';
import { DataGrid } from '@mui/x-data-grid';
import { ReportsService } from '../ReportsService.jsx'; // Adjusted path

// --- ProjectedReport COMPONENT (Uses fetched data) ---
const ProjectedReport = ({ businessRefId, isLoadingProfile, profileError }) => {
    const [projectedData, setProjectedData] = useState([]); const [isLoadingProjected, setIsLoadingProjected] = useState(true); const [projectedError, setProjectedError] = useState(null); const [searchText, setSearchText] = useState("");
    useEffect(() => { if (isLoadingProfile || profileError || !businessRefId) { if (!isLoadingProfile) { setIsLoadingProjected(false); if (profileError) setProjectedError(`Profile Error: ${profileError}`); else if (!businessRefId) setProjectedError("Business ID not found."); } else { setIsLoadingProjected(true); } return; } const fetchProjectedData = async () => { setIsLoadingProjected(true); setProjectedError(null); try { const data = await ReportsService.getVehicleReports(businessRefId); setProjectedData(data); console.log("Projected Savings Data Fetched:", data); } catch (err) { console.error("Failed to fetch projected savings:", err); setProjectedError(err.detail || "Could not load data."); setProjectedData([]); } finally { setIsLoadingProjected(false); } }; fetchProjectedData(); }, [businessRefId, isLoadingProfile, profileError]);
    const projectedColumns = useMemo(() => [{ field: 'vehicle_registration_no', headerName: 'Vehicle', flex: 1.5 }, { field: 'average_variance', headerName: 'Avg. Variance (km/l)', type: 'number', flex: 1, align: 'right', headerAlign: 'right', cellClassName: (params) => (params.value == null ? '' : params.value >= 0 ? 'positive-variance' : 'negative-variance'), valueFormatter: (value) => { if (typeof value !== 'number') return 'N/A'; return value >= 0 ? `+${value.toFixed(1)}` : value.toFixed(1); } }, { field: 'difference_kms', headerName: 'Difference in KMs', description: 'Estimated extra (+) or missed (-) KMs', type: 'number', flex: 1, align: 'right', headerAlign: 'right', cellClassName: (params) => (params.value == null ? '' : params.value >= 0 ? 'positive-variance' : 'negative-variance'), valueFormatter: (value) => { if (typeof value !== 'number') return '-'; return value >= 0 ? `+${value.toLocaleString(undefined, { maximumFractionDigits: 1 })}` : value.toLocaleString(undefined, { maximumFractionDigits: 1 }); } }, { field: 'financial_impact', headerName: 'Financial Impact (₹)', description: `Savings (+) or Loss (-) at ₹92/litre`, type: 'number', flex: 1, align: 'right', headerAlign: 'right', cellClassName: (params) => (params.value == null ? '' : params.value >= 0 ? 'positive-impact' : 'negative-impact'), valueFormatter: (value) => { if (typeof value !== 'number') return '-'; const formattedValue = Math.abs(value).toLocaleString(undefined, { maximumFractionDigits: 0 }); return value >= 0 ? `₹${formattedValue}` : `₹(${formattedValue})`; }, },], []);
    const filteredRows = useMemo(() => { if (!searchText) return projectedData; const lowerSearchText = searchText.toLowerCase(); return projectedData.filter((row) => row.vehicle_registration_no?.toLowerCase().includes(lowerSearchText)); }, [projectedData, searchText]);
    return (<Box> <div className="report-header"><h3>Projected Financial Impact</h3><div className="report-filters"><TextField size="small" variant="outlined" placeholder="Search Vehicle..." value={searchText} onChange={(e) => setSearchText(e.target.value)} InputProps={{ startAdornment: (<InputAdornment position="start"><SearchIcon fontSize="small" /></InputAdornment>), }} /></div></div> {isLoadingProjected && <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 350 }}><CircularProgress /><Typography sx={{ ml: 2 }}>Loading data...</Typography></Box>} {projectedError && !isLoadingProjected && <Alert severity="error" sx={{ my: 2 }}>{projectedError}</Alert>} {!isLoadingProjected && !projectedError && <div className="report-content"><Box sx={{ height: 400, width: '100%' }}><DataGrid rows={filteredRows} columns={projectedColumns} disableColumnResize={true} getRowId={(row) => row.id} initialState={{ pagination: { paginationModel: { pageSize: 10 } }, sorting: { sortModel: [{ field: 'financial_impact', sort: 'desc' }] }, }} pageSizeOptions={[10, 25, 50]} localeText={{ noRowsLabel: 'No data available.' }} /></Box></div>} </Box>);
};

export default ProjectedReport;