import React, { useState, useEffect, useMemo } from 'react';
import {
    Box, Typography, TextField, InputAdornment,
    Select, MenuItem, FormControl, InputLabel, CircularProgress, Alert,
} from '@mui/material';
import { Search as SearchIcon } from '@mui/icons-material';
import { DataGrid } from '@mui/x-data-grid';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import dayjs from 'dayjs';
import { ReportsService } from '../ReportsService.jsx'; // Adjusted path
import { months } from '../../../utils/mockdata.jsx'; // Adjusted path

// --- TripReport COMPONENT (Uses fetched data) ---
const TripReport = ({ businessRefId, isLoadingProfile, profileError }) => {
    const [tripData, setTripData] = useState([]); const [isLoadingTrips, setIsLoadingTrips] = useState(true); const [tripError, setTripError] = useState(null); const [searchText, setSearchText] = useState(""); const [dateRange, setDateRange] = useState([null, null]); const [selectedMonth, setSelectedMonth] = useState('');
    useEffect(() => { if (isLoadingProfile || profileError || !businessRefId) { if (!isLoadingProfile) { setIsLoadingTrips(false); if (profileError) setTripError(`Profile Error: ${profileError}`); else if (!businessRefId) setTripError("Business ID not found."); } else { setIsLoadingTrips(true); } return; } const fetchTrips = async () => { setIsLoadingTrips(true); setTripError(null); try { const data = await ReportsService.getTripReports(businessRefId); setTripData(data); console.log("Trip Reports Fetched:", data); } catch (err) { console.error("Failed to fetch trip reports:", err); setTripError(err.detail || "Could not load trip reports."); setTripData([]); } finally { setIsLoadingTrips(false); } }; fetchTrips(); }, [businessRefId, isLoadingProfile, profileError]);
    const tripColumns = useMemo(() => [{ field: 'start_date', headerName: 'Start Date', flex: 1, type: 'date', valueGetter: (value) => value ? dayjs(value).toDate() : null }, { field: 'end_date', headerName: 'End Date', flex: 1, type: 'date', valueGetter: (value) => value ? dayjs(value).toDate() : null }, { field: 'driver_name', headerName: 'Driver', flex: 1.5, valueGetter: (value) => value || 'N/A' }, { field: 'vehicle_registration_no', headerName: 'Vehicle', flex: 1 }, { field: 'kms_driven', headerName: 'KMs Driven', type: 'number', flex: 1, align: 'right', headerAlign: 'right', valueFormatter: (value) => typeof value === 'number' ? value.toFixed(1) : '-' }, { field: 'fleetedge_mileage_kml', headerName: 'FleetEdge (km/l)', type: 'number', flex: 1, align: 'right', headerAlign: 'right', valueFormatter: (value) => typeof value === 'number' ? value.toFixed(2) : '-' }, { field: 'bill_mileage_kml', headerName: 'Bill (km/l)', type: 'number', flex: 1, align: 'right', headerAlign: 'right', valueFormatter: (value) => typeof value === 'number' ? value.toFixed(2) : '-' }, { field: 'variance', headerName: 'Variance', type: 'number', flex: 1, align: 'right', headerAlign: 'right', renderCell: (params) => { const value = params.value; if (typeof value !== 'number') return '-'; return <span style={{ color: value > 0 ? 'green' : 'red', fontWeight: Math.abs(value) >= 1.5 ? 'bold' : 'normal' }}>{value > 0 ? `+${value.toFixed(1)}` : value.toFixed(1)}</span>; } },], []);
    const filteredRows = useMemo(() => {
        let rows = tripData; if (searchText) { const lowerSearchText = searchText.toLowerCase(); rows = rows.filter(row => row.driver_name?.toLowerCase().includes(lowerSearchText) || row.vehicle_registration_no?.toLowerCase().includes(lowerSearchText)); } const startDate = dateRange[0]; const endDate = dateRange[1]; if (startDate || endDate) {
            rows = rows.filter(row => {
                if (!row.start_date) return false; const rowStartDate = dayjs(row.start_date); const afterStart = startDate ? rowStartDate.isAfter(startDate.subtract(1, 'day')) : true; const beforeEnd = endDate ? rowStartDate.isBefore(endDate.add(1, 'day')) : true; return afterStart && beforeEnd;
            });
        } if (selectedMonth !== '') { rows = rows.filter(row => { if (!row.start_date) return false; return dayjs(row.start_date).month() === selectedMonth; }); } return rows;
    }, [tripData, searchText, dateRange, selectedMonth]);
    return (<Box> <div className="report-header"><h3>Trip Report</h3><div className="report-filters"><TextField size="small" variant="outlined" placeholder="Search Driver/Vehicle..." value={searchText} onChange={(e) => setSearchText(e.target.value)} InputProps={{ startAdornment: (<InputAdornment position="start"><SearchIcon fontSize="small" /></InputAdornment>), }} sx={{ width: 220 }} /><DatePicker label="Start Date" value={dateRange[0]} onChange={(newValue) => setDateRange([newValue, dateRange[1]])} slotProps={{ textField: { size: 'small' } }} /><DatePicker label="End Date" value={dateRange[1]} onChange={(newValue) => setDateRange([dateRange[0], newValue])} slotProps={{ textField: { size: 'small' } }} /><FormControl size="small" sx={{ minWidth: 150 }}><InputLabel>Month</InputLabel><Select value={selectedMonth} label="Month" onChange={(e) => setSelectedMonth(e.target.value)} ><MenuItem value=""><em>All Months</em></MenuItem>{months.map((month) => (<MenuItem key={month.value} value={month.value}>{month.label}</MenuItem>))}</Select></FormControl></div></div> {isLoadingTrips && <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 400 }}><CircularProgress /><Typography sx={{ ml: 2 }}>Loading trip data...</Typography></Box>} {tripError && !isLoadingTrips && <Alert severity="error" sx={{ my: 2 }}>{tripError}</Alert>} {!isLoadingTrips && !tripError && <div className="report-content"><Box sx={{ height: 600, width: '100%' }}><DataGrid rows={filteredRows} columns={tripColumns} disableColumnResize={true} initialState={{ pagination: { paginationModel: { pageSize: 15 } }, sorting: { sortModel: [{ field: 'start_date', sort: 'desc' }] }, }} pageSizeOptions={[15, 30, 50]} localeText={{ noRowsLabel: 'No trips found.' }} /></Box></div>} </Box>);
};

export default TripReport;